version: "3"
services:
  python:
    build: .
    depends_on:
      - localstack
    ports:
      - "9000:8080"

    environment:
      - AWS_ACCESS_KEY_ID=dummy
      - AWS_SECRET_ACCESS_KEY=dummy
      - AWS_REGION=ap-northeast-1
      - AWS_DEFAULT_REGION=ap-northeast-1
      - AWS_ENDPOINT_URL=http://localstack:4566

    working_dir: /root

  localstack:
    image: localstack/localstack:0.12.5
    ports:
      - "4566:4566"
      - "8080:8080"
    environment:
      - SERVICES=s3
      - DOCKER_HOST=unix:///var/run/docker.sock
      - DEFAULT_REGION=ap-northeast-1
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"

